
import type { LucideIcon } from "lucide-react";
import {
  FileText,
  Palette,
  Code2,
  ScanSearch,
  Wrench,
  CaseSensitive,
  FileImage,
  Search,
  Calculator,
  Type,
  Heading1,
  QrCode,
  ALargeSmall,
  Link2,
  ListRestart,
  KeyRound,
  Paintbrush,
  BookText,
  Lock,
  Bot,
  AudioLines,
  HeartPulse,
  Landmark,
  Scale,
  Ratio,
  Shrink,
  Pipette,
  FilePlus2,
  FileArchive,
  Scissors,
  ScanText,
  Coins,
  Timer,
  Keyboard,
  Layers,
  FileUp,
  FileEdit,
  FileDown,
  FileSpreadsheet,
  Presentation,
  Globe,
  Camera,
  FileCode,
  Edit,
  Scan,
  Hash,
  Unlock,
  TextQuote,
  Info,
  Combine,
} from "lucide-react";

// Define interfaces for our data structures
export interface Tool {
  id: string;
  name: string;
  slug: string;
  description: string;
  category: string;
  categorySlug: string;
  href: string;
  icon: LucideIcon;
  ai_powered?: boolean;
  is_featured?: boolean;
  popularity_score: number;
  created_at: Date;
  last_updated: Date;
}

export interface ToolCategory {
  id: string;
  name: string;
  slug: string;
  description: string;
  icon: LucideIcon;
}

const toolCategories: ToolCategory[] = [
  {
    id: "text-tools",
    name: "Text Tools",
    slug: "text-tools",
    description: "Tools for manipulating and analyzing text.",
    icon: FileText,
  },
  {
    id: "image-tools",
    name: "Image Tools",
    slug: "image-tools",
    description: "Tools for editing and converting images.",
    icon: FileImage,
  },
  {
    id: "developer-tools",
    name: "Developer Tools",
    slug: "developer-tools",
    description: "Tools for developers and programmers.",
    icon: Code2,
  },
  {
    id: "pdf-tools",
    name: "PDF Tools",
    slug: "pdf-tools",
    description: "Tools for working with PDF documents.",
    icon: FileArchive,
  },
  {
    id: "ai-tools",
    name: "AI Tools",
    slug: "ai-tools",
    description: "Harness the power of AI with these smart tools.",
    icon: Bot,
  },
  {
    id: "calculators",
    name: "Calculators",
    slug: "calculators",
    description: "Perform various calculations for finance, health, and more.",
    icon: Calculator,
  },
  {
    id: "converters",
    name: "Converters",
    slug: "converters",
    description: "Convert between different file formats and units.",
    icon: Wrench,
  },
];

const allTools: Tool[] = [
  {
    id: 'pdf-metadata-editor',
    name: 'PDF Metadata Editor',
    slug: 'pdf-metadata-editor',
    description: 'View and edit PDF metadata such as author, title, and subject.',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    href: '/tools/pdf-metadata-editor',
    icon: Info,
    is_featured: true,
    popularity_score: 98,
    created_at: new Date('2024-09-09T10:00:00Z'),
    last_updated: new Date('2024-09-09T10:00:00Z'),
  },
  {
    id: 'pdf-ocr',
    name: 'PDF OCR',
    slug: 'pdf-ocr',
    description: 'Extract text from scanned PDFs using AI-powered OCR.',
    category: 'AI Tools',
    categorySlug: 'ai-tools',
    href: '/tools/pdf-ocr',
    icon: Scan,
    ai_powered: true,
    is_featured: true,
    popularity_score: 100,
    created_at: new Date('2024-09-08T10:00:00Z'),
    last_updated: new Date('2024-09-08T10:00:00Z'),
  },
  {
    id: 'pdf-form-filler',
    name: 'PDF Form Filler',
    slug: 'pdf-form-filler',
    description: 'Fill out PDF forms directly in your browser.',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    href: '/tools/pdf-form-filler',
    icon: Edit,
    is_featured: true,
    popularity_score: 99,
    created_at: new Date('2024-09-07T10:00:00Z'),
    last_updated: new Date('2024-09-07T10:00:00Z'),
  },
  {
    id: "pdf-editor",
    name: "PDF Editor",
    slug: "pdf-editor",
    description: "Split, rotate, extract pages, rearrange, add page numbers, watermarks, flatten, headers, footers, and manage passwords.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    href: "/tools/pdf-editor",
    icon: FileEdit,
    is_featured: true,
    popularity_score: 98,
    created_at: new Date("2024-08-25T10:00:00Z"),
    last_updated: new Date("2024-08-25T10:00:00Z"),
  },
  {
    id: "plagiarism-checker",
    name: "Plagiarism Checker",
    slug: "plagiarism-checker",
    description: "Check text for plagiarism against online sources.",
    category: "AI Tools",
    categorySlug: "ai-tools",
    href: "/tools/plagiarism-checker",
    icon: ScanText,
    ai_powered: true,
    is_featured: true,
    popularity_score: 99,
    created_at: new Date("2024-08-14T10:00:00Z"),
    last_updated: new Date("2024-08-14T10:00:00Z"),
  },
  {
    id: "image-background-remover",
    name: "Image Background Remover",
    slug: "image-background-remover",
    description: "Automatically remove the background from any image.",
    category: "AI Tools",
    categorySlug: "ai-tools",
    href: "/tools/image-background-remover",
    icon: Scissors,
    ai_powered: true,
    is_featured: true,
    popularity_score: 98,
    created_at: new Date("2024-08-12T10:00:00Z"),
    last_updated: new Date("2024-08-12T10:00:00Z"),
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    slug: "word-to-pdf",
    description: "Convert Microsoft Word (.docx) files to PDF.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    href: "/tools/word-to-pdf",
    icon: FileText,
    is_featured: true,
    popularity_score: 97,
    created_at: new Date("2024-08-11T10:00:00Z"),
    last_updated: new Date("2024-08-11T10:00:00Z"),
  },
  {
    id: "excel-to-pdf",
    name: "Excel to PDF",
    slug: "excel-to-pdf",
    description: "Convert Microsoft Excel (.xlsx) files to PDF.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    href: "/tools/excel-to-pdf",
    icon: FileSpreadsheet,
    is_featured: true,
    popularity_score: 96,
    created_at: new Date("2024-08-30T10:00:00Z"),
    last_updated: new Date("2024-08-30T10:00:00Z"),
  },
  {
    id: 'powerpoint-to-pdf',
    name: 'PowerPoint to PDF',
    slug: 'powerpoint-to-pdf',
    description: 'Convert PowerPoint (.pptx) presentations to PDF.',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    href: '/tools/powerpoint-to-pdf',
    icon: Presentation,
    is_featured: true,
    popularity_score: 95,
    created_at: new Date('2024-08-31T10:00:00Z'),
    last_updated: new Date('2024-08-31T10:00:00Z'),
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word Converter",
    slug: "pdf-to-word",
    description: "Convert PDF documents to editable Word (.docx) files.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    href: "/tools/pdf-to-word",
    icon: FileDown,
    is_featured: true,
    popularity_score: 97,
    created_at: new Date("2024-08-29T10:00:00Z"),
    last_updated: new Date("2024-08-29T10:00:00Z"),
  },
   {
    id: "pdf-to-text",
    name: "PDF to Text Extractor",
    slug: "pdf-to-text",
    description: "Extract plain text from your PDF files.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    href: "/tools/pdf-to-text",
    icon: Type,
    popularity_score: 85,
    created_at: new Date("2024-08-29T11:00:00Z"),
    last_updated: new Date("2024-08-29T11:00:00Z"),
  },
    {
    id: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    slug: "pdf-to-powerpoint",
    description: "Convert PDF documents into editable PowerPoint (.pptx) files.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    href: "/tools/pdf-to-powerpoint",
    icon: Presentation,
    is_featured: false,
    popularity_score: 91,
    created_at: new Date("2024-09-05T10:00:00Z"),
    last_updated: new Date("2024-09-05T10:00:00Z"),
  },
  {
    id: "pdf-merger",
    name: "PDF Merger",
    slug: "pdf-merger",
    description: "Combine multiple PDF files into a single document.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    href: "/tools/pdf-merger",
    icon: FilePlus2,
    is_featured: true,
    popularity_score: 96,
    created_at: new Date("2024-08-10T10:00:00Z"),
    last_updated: new Date("2024-08-10T10:00:00Z"),
  },
  {
    id: "text-to-pdf",
    name: "Text to PDF",
    slug: "text-to-pdf",
    description: "Convert plain text or simple Markdown to a PDF document.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    href: "/tools/text-to-pdf",
    icon: FileText,
    popularity_score: 88,
    is_featured: false,
    created_at: new Date("2024-09-01T10:00:00Z"),
    last_updated: new Date("2024-09-01T10:00:00Z"),
  },
   {
    id: "html-to-pdf",
    name: "HTML to PDF Converter",
    slug: "html-to-pdf",
    description: "Convert any live webpage into a PDF document.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    href: "/tools/html-to-pdf",
    icon: Globe,
    popularity_score: 94,
    is_featured: true,
    created_at: new Date("2024-09-02T10:00:00Z"),
    last_updated: new Date("2024-09-02T10:00:00Z"),
  },
   {
    id: "scan-to-pdf",
    name: "Scan to PDF",
    slug: "scan-to-pdf",
    description: "Use your camera to scan documents and save them as a PDF.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    href: "/tools/scan-to-pdf",
    icon: Camera,
    popularity_score: 95,
    is_featured: true,
    created_at: new Date("2024-09-03T10:00:00Z"),
    last_updated: new Date("2024-09-03T10:00:00Z"),
  },
  {
    id: "pdf-to-excel",
    name: "PDF to Excel",
    slug: "pdf-to-excel",
    description: "Extract data from PDF tables into an Excel-compatible format.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    href: "/tools/pdf-to-excel",
    icon: FileSpreadsheet,
    is_featured: false,
    popularity_score: 90,
    created_at: new Date("2024-09-04T10:00:00Z"),
    last_updated: new Date("2024-09-04T10:00:00Z"),
  },
  {
    id: "pdf-to-image",
    name: "PDF to Image Converter",
    slug: "pdf-to-image",
    description: "Convert each page of a PDF document into JPG or PNG images.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    href: "/tools/pdf-to-image",
    icon: FileUp,
    popularity_score: 90,
    is_featured: true,
    created_at: new Date("2024-08-28T10:00:00Z"),
    last_updated: new Date("2024-08-28T10:00:00Z"),
  },
  {
    id: 'pdf-to-html',
    name: 'PDF to HTML',
    slug: 'pdf-to-html',
    description: 'Convert PDF files to structured HTML documents.',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    href: '/tools/pdf-to-html',
    icon: FileCode,
    is_featured: false,
    popularity_score: 89,
    created_at: new Date('2024-09-06T10:00:00Z'),
    last_updated: new Date('2024-09-06T10:00:00Z'),
  },
  {
    id: "password-generator",
    name: "Password Generator",
    slug: "password-generator",
    description: "Create strong, secure, and random passwords for your accounts.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    href: "/tools/password-generator",
    icon: Lock,
    is_featured: true,
    popularity_score: 95,
    created_at: new Date("2024-07-20T12:00:00Z"),
    last_updated: new Date("2024-07-20T12:00:00Z"),
  },
  {
    id: "meta-tag-generator",
    name: "Meta Tag Generator",
    slug: "meta-tag-generator",
    description: "Generate SEO-optimized meta tags for your website using AI.",
    category: "AI Tools",
    categorySlug: "ai-tools",
    href: "/tools/meta-tag-generator",
    icon: ScanSearch,
    ai_powered: true,
    is_featured: true,
    popularity_score: 94,
    created_at: new Date("2024-07-31T12:00:00Z"),
    last_updated: new Date("2024-07-31T12:00:00Z"),
  },
  {
    id: "code-formatter",
    name: "Code Formatter",
    slug: "code-formatter",
    description: "Format, validate, and beautify your JSON, HTML, CSS, and JS.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    href: "/tools/code-formatter",
    icon: Code2,
    is_featured: true,
    popularity_score: 93,
    created_at: new Date("2024-07-18T12:00:00Z"),
    last_updated: new Date("2024-08-22T12:00:00Z"),
  },
  {
    id: "loan-calculator",
    name: "Loan Calculator",
    slug: "loan-calculator",
    description: "Estimate your monthly loan payments and total interest.",
    category: "Calculators",
    categorySlug: "calculators",
    href: "/tools/loan-calculator",
    icon: Landmark,
    is_featured: true,
    popularity_score: 92,
    created_at: new Date("2024-07-26T12:00:00Z"),
    last_updated: new Date("2024-07-26T12:00:00Z"),
  },
  {
    id: "image-converter",
    name: "Image Converter",
    slug: "image-converter",
    description: "Convert images between JPG, PNG, WEBP, and other formats.",
    category: "Image Tools",
    categorySlug: "image-tools",
    href: "/tools/image-converter",
    icon: FileImage,
    is_featured: true,
    popularity_score: 91,
    created_at: new Date("2024-07-30T11:00:00Z"),
    last_updated: new Date("2024-07-30T11:00:00Z"),
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    slug: "image-compressor",
    description: "Reduce image file sizes for faster web pages.",
    category: "Image Tools",
    categorySlug: "image-tools",
    href: "/tools/image-compressor",
    icon: Shrink,
    popularity_score: 90,
    is_featured: true,
    created_at: new Date("2024-08-03T10:00:00Z"),
    last_updated: new Date("2024-08-03T10:00:00Z"),
  },
  {
    id: "text-to-speech",
    name: "Text-to-Speech Converter",
    slug: "text-to-speech",
    description: "Convert text into natural-sounding speech with our AI-powered TTS tool.",
    category: "AI Tools",
    categorySlug: "ai-tools",
    href: "/tools/text-to-speech",
    icon: AudioLines,
    ai_powered: true,
    is_featured: true,
    popularity_score: 90,
    created_at: new Date("2024-07-28T12:00:00Z"),
    last_updated: new Date("2024-07-28T12:00:00Z"),
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    slug: "unit-converter",
    description: "Convert between various units of measurement like length, weight, etc.",
    category: "Converters",
    categorySlug: "converters",
    href: "/tools/unit-converter",
    icon: Scale,
    popularity_score: 89,
    is_featured: true,
    created_at: new Date("2024-08-01T10:00:00Z"),
    last_updated: new Date("2024-08-01T10:00:00Z"),
  },
   {
    id: "image-to-pdf",
    name: "Image to PDF Converter",
    slug: "image-to-pdf",
    description: "Easily convert JPG, PNG, and WEBP images to PDF documents.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    href: "/tools/image-to-pdf",
    icon: FileImage,
    popularity_score: 89,
    is_featured: false,
    created_at: new Date("2024-08-23T10:00:00Z"),
    last_updated: new Date("2024-08-23T10:00:00Z"),
  },
  {
    id: "currency-converter",
    name: "Currency Converter",
    slug: "currency-converter",
    description: "Convert amounts between different currencies.",
    category: "Converters",
    categorySlug: "converters",
    href: "/tools/currency-converter",
    icon: Coins,
    popularity_score: 88,
    is_featured: true,
    created_at: new Date("2024-08-16T10:00:00Z"),
    last_updated: new Date("2024-08-16T10:00:00Z"),
  },
  {
    id: "bmi-calculator",
    name: "BMI Calculator",
    slug: "bmi-calculator",
    description: "Check your Body Mass Index to assess your health.",
    category: "Calculators",
    categorySlug: "calculators",
    href: "/tools/bmi-calculator",
    icon: HeartPulse,
    popularity_score: 88,
    created_at: new Date("2024-07-27T12:00:00Z"),
    last_updated: new Date("2024-07-27T12:00:00Z"),
  },
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    slug: "qr-code-generator",
    description: "Create custom QR codes for URLs, text, and more.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    href: "/tools/qr-code-generator",
    icon: QrCode,
    popularity_score: 87,
    created_at: new Date("2024-07-30T10:00:00Z"),
    last_updated: new Date("2024-07-30T10:00:00Z"),
  },
  {
    id: "image-resizer",
    name: "Image Resizer",
    slug: "image-resizer",
    description: "Easily change the dimensions of your images online.",
    category: "Image Tools",
    categorySlug: "image-tools",
    href: "/tools/image-resizer",
    icon: Ratio,
    popularity_score: 86,
    is_featured: true,
    created_at: new Date("2024-08-02T10:00:00Z"),
    last_updated: new Date("2024-08-02T10:00:00Z"),
  },
  {
    id: "case-converter",
    name: "Case Converter",
    slug: "case-converter",
    description: "Change text to uppercase, lowercase, title case, and more.",
    category: "Text Tools",
    categorySlug: "text-tools",
    href: "/tools/case-converter",
    icon: CaseSensitive,
    is_featured: true,
    popularity_score: 85,
    created_at: new Date("2024-07-25T12:00:00Z"),
    last_updated: new Date("2024-07-25T12:00:00Z"),
  },
  {
    id: "color-converter",
    name: "Color Converter",
    slug: "color-converter",
    description: "Convert colors between HEX, RGB, and HSL formats.",
    category: "Converters",
    categorySlug: "converters",
    href: "/tools/color-converter",
    icon: Palette,
    popularity_score: 84,
    created_at: new Date("2024-07-30T12:00:00Z"),
    last_updated: new Date("2024-07-30T12:00:00Z"),
  },
  {
    id: "color-picker",
    name: "Color Picker",
    slug: "color-picker",
    description: "Select colors from a visual picker and get their codes.",
    category: "Converters",
    categorySlug: "converters",
    href: "/tools/color-picker",
    icon: Pipette,
    popularity_score: 83,
    is_featured: false,
    created_at: new Date("2024-08-05T10:00:00Z"),
    last_updated: new Date("2024-08-05T10:00:00Z"),
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    slug: "uuid-generator",
    description: "Generate universally unique identifiers (UUIDs) instantly.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    href: "/tools/uuid-generator",
    icon: KeyRound,
    popularity_score: 82,
    created_at: new Date("2024-07-21T12:00:00Z"),
    last_updated: new Date("2024-07-21T12:00:00Z"),
  },
  {
    id: "word-counter",
    name: "Word Counter",
    slug: "word-counter",
    description: "Count words, characters, sentences, and paragraphs in your text.",
    category: "Text Tools",
    categorySlug: "text-tools",
    href: "/tools/word-counter",
    icon: ALargeSmall,
    popularity_score: 80,
    created_at: new Date("2024-07-24T12:00:00Z"),
    last_updated: new Date("2024-07-24T12:00:00Z"),
  },
  {
    id: "slug-generator",
    name: "Slug Generator",
    slug: "slug-generator",
    description: "Create clean, URL-friendly slugs from any text string.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    href: "/tools/slug-generator",
    icon: Link2,
    popularity_score: 78,
    created_at: new Date("2024-07-22T12:00:00Z"),
    last_updated: new Date("2024-07-22T12:00:00Z"),
  },
  {
    id: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    slug: "lorem-ipsum-generator",
    description: "Generate placeholder text for your designs and mockups.",
    category: "Text Tools",
    categorySlug: "text-tools",
    href: "/tools/lorem-ipsum-generator",
    icon: BookText,
    popularity_score: 75,
    created_at: new Date("2024-07-23T12:00:00Z"),
    last_updated: new Date("2024-07-23T12:00:00Z"),
  },
  {
    id: "palindrome-checker",
    name: "Palindrome Checker",
    slug: "palindrome-checker",
    description: "Check if a word, phrase, or number is a palindrome.",
    category: "Text Tools",
    categorySlug: "text-tools",
    href: "/tools/palindrome-checker",
    icon: ListRestart,
    popularity_score: 70,
    created_at: new Date("2024-07-19T12:00:00Z"),
    last_updated: new Date("2024-07-19T12:00:00Z"),
  },
  {
    id: "stopwatch-timer",
    name: "Stopwatch & Timer",
    slug: "stopwatch-timer",
    description: "An easy-to-use stopwatch and timer for tracking time.",
    category: "Calculators",
    categorySlug: "calculators",
    href: "/tools/stopwatch-timer",
    icon: Timer,
    popularity_score: 72,
    created_at: new Date("2024-08-20T10:00:00Z"),
    last_updated: new Date("2024-08-20T10:00:00Z"),
  },
   {
    id: "typing-speed-test",
    name: "Typing Speed Test",
    slug: "typing-speed-test",
    description: "Test your typing speed and accuracy with this fun game.",
    category: "Text Tools",
    categorySlug: "text-tools",
    href: "/tools/typing-speed-test",
    icon: Keyboard,
    popularity_score: 78,
    created_at: new Date("2024-08-21T10:00:00Z"),
    last_updated: new Date("2024-08-21T10:00:00Z"),
  },
];

// Function to get tools (now from local array)
export async function getTools(): Promise<Tool[]> {
  // Sort by popularity score by default
  const sortedTools = allTools.sort((a, b) => b.popularity_score - a.popularity_score);
  return Promise.resolve(sortedTools);
}

// Function to get categories (now from local array)
export async function getToolCategories(): Promise<ToolCategory[]> {
  return Promise.resolve(toolCategories);
}
