
"use client";

import { useState, useEffect } from 'react';
import { useFormState, useFormStatus } from 'react-dom';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useToast } from "@/hooks/use-toast";
import { Upload, Download, Loader2, Trash2, Presentation } from "lucide-react";
import { convertPdfToPowerpoint } from './actions';

function SubmitButton() {
  const { pending } = useFormStatus();
  return (
    <Button type="submit" disabled={pending} className="w-full">
      {pending ? (
        <>
          <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          Converting...
        </>
      ) : (
        <>
          <Presentation className="mr-2 h-4 w-4" />
          Convert to PowerPoint
        </>
      )}
    </Button>
  );
}

export default function PdfToPowerpointPage() {
  const [state, formAction] = useFormState(convertPdfToPowerpoint, {});
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const { toast } = useToast();

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files && event.target.files[0]) {
      const file = event.target.files[0];
      if (file.type === 'application/pdf') {
        setSelectedFile(file);
      } else {
        toast({ variant: "destructive", title: "Invalid File Type", description: "Only PDF files are accepted." });
        handleClear();
      }
    }
  };
  
  const handleDownload = () => {
    if (!state.fileDataUri || !selectedFile) return;

    // This downloads the sample PDF generated by the placeholder action.
    const link = document.createElement("a");
    link.href = state.fileDataUri;
    // Note: The download will be a sample PDF, not a .pptx file.
    const newName = state.fileName || selectedFile.name.replace(/\.pdf$/i, '.pdf');
    link.download = newName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast({ title: "Downloaded Sample PDF", description: "True .pptx conversion coming soon!" });
  };
  
  const handleClear = () => {
    setSelectedFile(null);
    const fileInput = document.getElementById('file-upload') as HTMLInputElement;
    if (fileInput) fileInput.value = "";
    formAction({}); // Clear state
  }

  useEffect(() => {
    if (state?.error) {
       toast({ variant: "destructive", title: "Conversion Failed", description: state.error });
    }
    if (state?.fileDataUri) {
         toast({ title: "Conversion Successful!", description: "A sample of your converted document is ready." });
    }
  }, [state, toast]);

  return (
    <div className="container mx-auto px-4 py-8 md:px-6">
      <div className="text-center mb-8">
        <h1 className="text-4xl font-bold font-headline">PDF to PowerPoint Converter</h1>
        <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
          Convert your PDF to an editable PowerPoint presentation. Note: This feature is in beta.
        </p>
      </div>

      <Card className="max-w-xl mx-auto">
        <form action={formAction}>
            <CardHeader>
                <CardTitle>Upload PDF</CardTitle>
                <CardDescription>Select the PDF file you want to convert to PowerPoint.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
                <div className="border-2 border-dashed border-muted-foreground/50 rounded-lg p-8 text-center">
                    <label htmlFor="file-upload" className="cursor-pointer">
                        <Upload className="mx-auto h-12 w-12 text-muted-foreground" />
                        <p className="mt-4 text-muted-foreground">{selectedFile ? `Selected: ${selectedFile.name}` : "Click to browse or drag and drop a PDF"}</p>
                    </label>
                    <Input
                        id="file-upload"
                        name="pdf"
                        type="file"
                        className="hidden"
                        onChange={handleFileChange}
                        accept="application/pdf"
                        required
                    />
                </div>
                
                {selectedFile && (
                    <div className="flex gap-2">
                        <SubmitButton />
                        <Button onClick={handleClear} variant="outline" type="button">
                            <Trash2 className="mr-2 h-4 w-4" />
                            Clear
                        </Button>
                    </div>
                )}
                
                {state.fileDataUri && (
                    <Button onClick={handleDownload} variant="secondary" className="w-full" type="button">
                        <Download className="mr-2 h-4 w-4" /> Download Sample
                    </Button>
                )}
            </CardContent>
        </form>
      </Card>
    </div>
  );
}
